[tool.poetry]
name = "bandcamp-downloader"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
beautifulsoup4 = "^4.12.2"
curl_cffi = "^0.7.3"
browser-cookie3 = "^0.14.0"
tqdm = "^4.64.0"

[tool.poetry.dev-dependencies]
